### ISSUE TITLE
READMEに利用方法を追記

### ISSUE THREAD

**Issue by rilmayer** [koji-inui/arxiv_pop#3]
コードと構成図だけだと、どのようにこのコード類を使えば良いか分からないので `README` にインストール方法や設定等のチュートリアルがあると良いかと思いました！（documentで切り出すか、qiita等の記事でまとめるのが良いかもです）
例えば、以下のような感じですかね〜。

---
## 環境構築
- AWSの〜でほげほげ
- 次にAWSの〜でほげほげ
- ...

## 環境変数の設定
- Twitter
- slack

## セットアップ
```
pip install -r requirements.txt
```

## dockerのビルド
```
docker build ./ -t arxiv_pop
```

**Comment by rilmayer** [comment]
↑ ProjectsのTODOに入ってましたね！

**Comment by koji-inui** [comment]
@rilmayer 
いや、Todoに入ってたのは、構成図の挿入までだったw

Dockerfileの追加と、Readmeの更新をTodoに入れる。
あざます！
